# Generated by Django 5.0.7 on 2024-09-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
