# Generated by Django 4.1.13 on 2024-09-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_alter_vacante_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
